# Generated by Django 5.1.3 on 2024-11-20 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, null=True, verbose_name='О себе')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profiles/avatars/', verbose_name='Аватар')),
                ('friends_qty', models.PositiveIntegerField(default=0, verbose_name='Кол-во друзей')),
                ('streams_qty', models.PositiveIntegerField(default=0, verbose_name='Кол-во стримов')),
                ('downloads_qty', models.PositiveIntegerField(default=0, verbose_name='Кол-во скачиваний игр')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
