# Generated by Django 5.1.3 on 2024-11-23 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='games/images/', verbose_name='Фото')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.game', verbose_name='Игра')),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='previews/streams', verbose_name='Превью')),
                ('viewers', models.PositiveIntegerField(default=0, verbose_name='Кол-во зрителей')),
                ('is_live', models.BooleanField(default=False, verbose_name='Онлайн')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата старта')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='home.game', verbose_name='Игра')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Стрим',
                'verbose_name_plural': 'Стримы',
            },
        ),
    ]
