# Generated by Django 5.1.3 on 2024-12-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_gameimage_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclip',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='clips/previews/', verbose_name='Превью'),
        ),
    ]
